project_id = "pxilycwmsbejejzbeedd"

[functions.notify-comment]
verify_jwt = false

[functions.send-telegram]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.razorpay-payment]
verify_jwt = false
